# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run a multi-line script
      run: |
        echo ${GITHUB_EVENT_NAME}
        echo ${GITHUB_EVENT_PATH}
        echo ${GITHUB_WORKSPACE}
        echo ${GITHUB_WORKFLOW}
        echo ${GITHUB_ACTION}
        echo ${GITHUB_ACTIONS}
        echo ${GITHUB_ACTOR}
        echo ${GITHUB_REPOSITORY}
        echo ${GITHUB_REF}
        if [ "workflow_dispatch" = ${GITHUB_EVENT_NAME} ]; then
          echo "workflow_dispatch!!!"
          GITHUB_REF="replaced-path"
        fi
        if [ "schedule" = ${GITHUB_EVENT_NAME} ]; then
          echo "schedule!!!"
          GITHUB_REF="replaced-path"
        fi
        echo ${GITHUB_REF}
