name: PR auto merge & notify security update
on:
  pull_request:
    types: [opened, reopened, labeled]

jobs:
  label:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: check labels
        id: labels
        run: |
          depfu=false
          security=false
          IFS=$'\n';for label in $(gh pr view ${{ github.event.pull_request.html_url }} --json labels --jq ".labels[].name"); do
            if [ ${label} = "depfu" ]; then
              depfu=true
            elif [ ${label} = "security" ]; then
              security=true
            fi
          done
          echo "::set-output name=IS_DEPFU::${depfu}"
          echo "::set-output name=IS_SECURITY::${security}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: auto merge
        if: ${{ steps.labels.outputs.IS_DEPFU == true }} && ${{ steps.labels.outputs.IS_SECURITY == false }}
        run: gh pr merge ${{ github.event.pull_request.html_url }} --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: notify security update
        if: ${{ steps.labels.outputs.IS_SECURITY == true }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              username: 'depfu',
              channel: 'dev'
              icon_emoji: ':rotating_light:',
              attachments: [{
                color: '${{ steps.variables.outputs.COLOR }}',
                title: 'セキュリティアップデート',
                text: 'セキュリティアップデートが作成されました',
                fields: [{
                  title: 'link',
                  value: '${{ github.event.pull_request.html_url }}',
                  short: true
                }]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
