name: CheckLabel
on:
  pull_request:
    types: [opened, reopened, labeled]

jobs:
  label:

    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: echo context
      run: echo '${{ toJSON(github) }}'
