name: CheckLabel
on:
  pull_request:
    types: [opened, reopened, labeled]

jobs:
  label:

    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: echo context
      run: echo '${{ toJSON(github) }}'

    - name: echo context
      run: |
        url=${{ github.event.pull_request.html_url }}
        echo "url:${url}"
        pr=$(gh pr view ${url})
        echo "pr:${pr}"
        echo $url
        echo $pr
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
