name: PR auto merge & notify security update
on:
  pull_request:
    types: [opened, reopened, labeled]

jobs:
  label:
    runs-on: ubuntu-20.04
    permissions: write-all

    steps:
      - name: check labels
        id: labels
        run: |
          depfu=false
          security=false
          IFS=$'\n';for label in $(gh pr view ${{ github.event.pull_request.html_url }} --json labels --jq ".labels[].name"); do
            echo "label:#{label}"
            if [ ${label} = "depfu" ]; then
              echo "depfu->true"
              depfu=true
            elif [ ${label} = "security" ]; then
              echo "security->true"
              security=true
            fi
          done
          echo "depfu:${depfu}"
          echo "security:${security}"
          echo "::set-output name=IS_DEPFU::${depfu}"
          echo "::set-output name=IS_SECURITY::${security}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: auto merge
        if: ${{ steps.labels.outputs.IS_DEPFU == 'true' && !steps.labels.outputs.IS_SECURITY == 'false' }}
        run: gh pr merge ${{ github.event.pull_request.html_url }} --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: notify security update
        if: ${{ steps.labels.outputs.IS_SECURITY == 'true }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              username: 'depfu',
              channel: 'dev-notifications',
              icon_emoji: ':rotating_light:',
              attachments: [{
                color: 'danger',
                title: 'セキュリティアップデート',
                text: '@okazaki セキュリティアップデートが作成されました',
                fields: [{
                  title: '${{ github.event.pull_request.title }}',
                  value: '${{ github.event.pull_request.html_url }}',
                  short: true
                }]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
