name: Labeler
on:
  pull_request:
    branches:
      - master

jobs:
  label:

    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: echo context
      run: echo '${{ toJSON(github) }}'
