on:
  push:
name: Run test case
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  backend-test:
    name: backend test
    runs-on: ubuntu-18.04
    if: (startsWith(github.ref, 'refs/heads/snyk-') != true) || (endsWith(github.ref, 'front-only') != true)

    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v2

  frontend-test:
    name: frontend test
    runs-on: ubuntu-18.04
    if: (startsWith(github.ref , 'refs/heads/depfu') != true) || (endsWith(github.ref, 'back-only') != true)

    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v2

  slack:
    name: slack
    runs-on: ubuntu-18.04
    needs:
      - backend-test
      - frontend-test
    if: always()

    steps:
      - name: github
        run: echo '${{ toJson(github) }}'

      - name: job
        run: echo '${{ toJson(job) }}'

      - name: steps
        run: echo '${{ toJson(steps) }}'

      - name: runner
        run: echo '${{ toJson(runner) }}'

      - name: strategy
        run: echo '${{ toJson(strategy) }}'

      - name: needs
        run: |
          echo '${{ toJson(needs) }}'
          echo '${{ (needs.backend-test.result == 'success' && needs.frontend-test.result == 'success') ? 'success' : 'failed' }}'

      - name: matrix
        run: echo '${{ toJson(matrix) }}'
