name: run from Other workflow
on:
  workflow_run:
    workflows: ["First workflow"]
    branches: [master]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging
